---

version: '3.4'

x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "${LOGGING_MAX_SIZE}"
    max-file: "${LOGGING_MAX_FILE}"

services:
  phpldapadmin_gatekeeper:
    image: "${KEYCLOAK_GATEKEEPER_IMAGE_NAME}:${KEYCLOAK_GATEKEEPER_IMAGE_VERSION}"
    command:
      - '--config=/etc/gatekeeper.yml'
    restart: 'unless-stopped'
    logging: *default-logging
    expose:
      - '3000'
    networks:
      - 'openldap'
      - 'services'
    volumes:
      - './config/gatekeepers/phpldapadmin.yml:/etc/gatekeeper.yml'
